from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
from reportlab.lib import colors
from io import BytesIO
import pandas as pd
from datetime import datetime

def generate_pdf_report(username, projects_data, score_data, insights, bio=None):
    """
    Generate a PDF report for a GitHub user
    """
    
    # Create PDF in memory
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.5*inch, bottomMargin=0.5*inch)
    
    # Container for PDF elements
    elements = []
    
    # Get styles
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#1f2937'),
        spaceAfter=6
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor('#374151'),
        spaceAfter=12
    )
    
    # Title
    elements.append(Paragraph(f"GitHub Stats Report: @{username}", title_style))
    elements.append(Paragraph(f"Generated on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}", styles['Normal']))
    elements.append(Spacer(1, 0.3*inch))
    
    # Developer Score Section
    elements.append(Paragraph("Developer Profile Score", heading_style))
    
    score_data_table = [
        ['Metric', 'Score'],
        ['Overall Score', f"{score_data['total_score']}/100"],
        ['Stars Score', f"{score_data['star_score']}/30"],
        ['Activity Score', f"{score_data['activity_score']}/25"],
        ['Diversity Score', f"{score_data['diversity_score']}/20"],
        ['Maturity Score', f"{score_data['maturity_score']}/15"],
        ['Consistency Score', f"{score_data['consistency_score']}/10"],
    ]
    
    score_table = Table(score_data_table, colWidths=[3*inch, 2*inch])
    score_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#374151')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    
    elements.append(score_table)
    elements.append(Spacer(1, 0.2*inch))
    
    # Bio Section
    if bio:
        elements.append(Paragraph("AI-Generated Developer Bio", heading_style))
        elements.append(Paragraph(bio, styles['Normal']))
        elements.append(Spacer(1, 0.2*inch))
    
    # Key Insights
    elements.append(Paragraph("Key Insights", heading_style))
    
    insights_text = f"""
    <b>Total Projects:</b> {insights['total_projects']}<br/>
    <b>Total Stars:</b> {insights['total_stars']}<br/>
    <b>Total Commits:</b> {insights['total_commits']}<br/>
    <b>Average Stars per Project:</b> {insights['avg_stars_per_project']}<br/>
    <b>Primary Languages:</b> {', '.join(list(insights['top_languages'].keys()))}<br/>
    <b>Most Successful Project:</b> {insights['most_successful_repo']} ({insights['most_successful_repo_stars']} ⭐)<br/>
    """
    
    elements.append(Paragraph(insights_text, styles['Normal']))
    elements.append(Spacer(1, 0.3*inch))
    
    # Top Repositories
    elements.append(Paragraph("Top 10 Repositories", heading_style))
    
    df = pd.DataFrame(projects_data, columns=['ID', 'Name', 'Description', 'Stars', 'Forks', 'Language', 'Commits', 'URL', 'Created', 'Updated'])
    top_repos = df.nlargest(10, 'Stars')
    
    repo_data = [['Repository', 'Stars', 'Forks', 'Language', 'Commits']]
    for _, repo in top_repos.iterrows():
        repo_data.append([
            repo['Name'][:20],
            str(repo['Stars']),
            str(repo['Forks']),
            repo['Language'],
            str(repo['Commits'])
        ])
    
    repo_table = Table(repo_data, colWidths=[1.5*inch, 0.8*inch, 0.8*inch, 0.8*inch, 0.8*inch])
    repo_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#374151')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.lightgrey),
        ('GRID', (0, 0), (-1, -1), 1, colors.grey)
    ]))
    
    elements.append(repo_table)
    elements.append(Spacer(1, 0.3*inch))
    
    # Footer
    elements.append(Paragraph(f"Report generated by GitHub Stats Dashboard", styles['Normal']))
    
    # Build PDF
    doc.build(elements)
    buffer.seek(0)
    
    return buffer